# Generated by Django 3.0.2 on 2020-03-05 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisposeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OccurPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='-', max_length=50)),
                ('_ID', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperateNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_ID', models.CharField(max_length=100)),
                ('main_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_type', to='event.MainType')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_ID', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='street', to='event.District')),
            ],
        ),
        migrations.AddField(
            model_name='maintype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_type', to='event.Type'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('achive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.Achieve')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.Community')),
                ('dispose_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.District')),
                ('event_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.EventSource')),
                ('occur_place', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.OccurPlace')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.Property')),
                ('report_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.OperateNumber')),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.SubType')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='event.Street'),
        ),
    ]
