# Generated by Django 2.2.3 on 2020-05-29 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aID', models.CharField(max_length=100)),
                ('long', models.FloatField(blank=True, default=0.0)),
                ('lat', models.FloatField(blank=True, default=0.0)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DisposeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposer', models.CharField(max_length=100)),
                ('create_time', models.DateField(default=django.utils.timezone.now)),
                ('eventID', models.CharField(default=0, max_length=100)),
            ],
            options={
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='DisposeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aID', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aID', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aID', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MainType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aID', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OccurPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='-', max_length=50)),
                ('aID', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperateNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(default=1)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PostRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=100)),
                ('create_time', models.DateField(default=django.utils.timezone.now)),
                ('eventID', models.CharField(default=0, max_length=100)),
            ],
            options={
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aID', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReportNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(default=1)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aID', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aID', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
                ('main_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_type', to='event.MainType')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aID', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='street', to='event.District')),
            ],
        ),
        migrations.AddField(
            model_name='maintype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_type', to='event.Type'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateField(default=django.utils.timezone.now)),
                ('achieve', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.Achieve')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.Community')),
                ('dispose_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.DisposeUnit')),
                ('event_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.EventSource')),
                ('occur_place', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.OccurPlace')),
                ('operate_num', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.OperateNumber')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.Property')),
                ('report_num', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.ReportNumber')),
                ('sub_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.SubType')),
                ('type', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.Type')),
            ],
            options={
                'ordering': ('-create_time',),
            },
        ),
        migrations.AddField(
            model_name='community',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='event.Street'),
        ),
    ]
