# Generated by Django 2.2.3 on 2020-05-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposerecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postrecord',
            options={},
        ),
    ]
