# Generated by Django 3.0.2 on 2020-03-05 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200305_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='_ID',
            new_name='aID',
        ),
        migrations.RenameField(
            model_name='disposeunit',
            old_name='_ID',
            new_name='aID',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='_ID',
            new_name='aID',
        ),
        migrations.RenameField(
            model_name='eventsource',
            old_name='_ID',
            new_name='aID',
        ),
        migrations.RenameField(
            model_name='maintype',
            old_name='_ID',
            new_name='aID',
        ),
        migrations.RenameField(
            model_name='occurplace',
            old_name='_ID',
            new_name='aID',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='_ID',
            new_name='aID',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='_ID',
            new_name='aID',
        ),
        migrations.RenameField(
            model_name='subtype',
            old_name='_ID',
            new_name='aID',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='_ID',
            new_name='aID',
        ),
        migrations.AlterField(
            model_name='event',
            name='achive',
            field=models.ForeignKey(default='intime_to', on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.Achieve'),
        ),
    ]
