# Generated by Django 3.0.4 on 2020-03-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200314_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.Type'),
        ),
    ]
