# Generated by Django 3.0.2 on 2020-03-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200305_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dispose_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.DisposeUnit'),
        ),
    ]
