# Generated by Django 3.0.2 on 2020-03-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200305_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='occur_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.OccurPlace'),
        ),
    ]
