# Generated by Django 3.0.2 on 2020-03-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200305_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='achive',
            new_name='achieve',
        ),
    ]
