# Generated by Django 3.0.2 on 2020-03-07 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20200305_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
