# Generated by Django 3.0.2 on 2020-03-07 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20200307_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
