# Generated by Django 3.0.2 on 2020-03-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20200307_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='achieve',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
