# Generated by Django 3.0.2 on 2020-03-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_achieve_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='lat',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='community',
            name='long',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
