# Generated by Django 2.2.3 on 2020-04-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200412_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmstring',
            name='password',
        ),
    ]
