# Generated by Django 2.2.3 on 2020-04-26 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_confirmstring_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmstring',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_string', to=settings.AUTH_USER_MODEL),
        ),
    ]
