# Generated by Django 2.2.3 on 2020-05-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200426_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_disposer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_poster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='unit',
            field=models.TextField(blank=True),
        ),
    ]
