# Generated by Django 2.2.3 on 2020-05-16 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_applylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='validation',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applylist', to=settings.AUTH_USER_MODEL),
        ),
    ]
