# Generated by Django 2.2.3 on 2020-05-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_disposerecord_postrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposerecord',
            options={'ordering': ('create_time',)},
        ),
        migrations.AlterModelOptions(
            name='postrecord',
            options={'ordering': ('create_time',)},
        ),
    ]
